"""
Streamlit portal for patient feedback submission and clinician dashboards.
Consumes the live FastAPI backend (no mocked responses).
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional

import altair as alt
import pandas as pd
import requests
import streamlit as st

API_BASE_URL: str = os.getenv("API_BASE_URL", "http://127.0.0.1:8000").rstrip("/")

DISCLAIMER_FALLBACK = (
    "This output is generated by an AI-assisted decision support system. "
    "It is advisory only. The final clinical decision must always be made by "
    "a qualified healthcare professional."
)


def _get(path: str, params: Optional[Dict[str, Any]] = None) -> requests.Response:
    return requests.get(f"{API_BASE_URL}{path}", params=params or {}, timeout=60)


def _post(path: str, json_body: Dict[str, Any]) -> requests.Response:
    return requests.post(f"{API_BASE_URL}{path}", json=json_body, timeout=120)


def risk_color(label: str) -> str:
    """Map risk label to a simple color token for UI styling."""
    if label == "Severe Adverse Reaction":
        return "red"
    if label == "Moderate Risk":
        return "orange"
    return "green"


def main() -> None:
    st.set_page_config(page_title="SE-CDSS", layout="wide")
    st.title("SE-CDSS — Clinical decision support (advisory)")
    st.caption(f"API: `{API_BASE_URL}`")

    tab_patient, tab_clinician = st.tabs(["Patient portal", "Clinician dashboard"])

    with tab_patient:
        st.subheader("Submit medication feedback")
        review = st.text_area("Your experience with the medication", height=160)
        patient_id = st.text_input("Patient ID (optional)", value="P-PORTAL-1")
        drug_name = st.text_input("Drug name (optional)", value="")
        condition = st.text_input("Condition (optional)", value="")

        if st.button("Analyze feedback", type="primary"):
            if not review.strip():
                st.warning("Please enter review text.")
            else:
                payload: Dict[str, Any] = {"review": review.strip()}
                if patient_id.strip():
                    payload["patient_id"] = patient_id.strip()
                if drug_name.strip():
                    payload["drug_name"] = drug_name.strip()
                if condition.strip():
                    payload["condition"] = condition.strip()
                try:
                    resp = _post("/api/feedback", payload)
                except requests.RequestException as exc:
                    st.error(f"Could not reach API: {exc}")
                    return
                if resp.status_code != 200:
                    st.error(f"API error {resp.status_code}: {resp.text}")
                    return
                data = resp.json()
                color = risk_color(data.get("risk_level", ""))
                st.metric("Sentiment", data.get("sentiment", "—"))
                st.metric("Confidence", f"{float(data.get('confidence', 0)):.2f}")
                st.markdown(
                    f"**Risk level:** :{color}[{data.get('risk_level', '—')}]"
                )
                st.json(data.get("probabilities", {}))
                st.info(data.get("disclaimer") or DISCLAIMER_FALLBACK)

    with tab_clinician:
        st.subheader("Recommendations and longitudinal trends")
        cid = st.text_input("Patient ID", value="P-00001")
        cond = st.selectbox(
            "Condition",
            [
                "hypertension",
                "diabetes",
                "depression",
                "malaria",
                "respiratory",
            ],
        )
        sent = st.selectbox("Latest sentiment", ["positive", "neutral", "negative"])

        col_a, col_b = st.columns(2)
        with col_a:
            if st.button("Fetch recommendations"):
                try:
                    r = _get(
                        "/api/recommend",
                        {
                            "condition": cond,
                            "patient_id": cid.strip(),
                            "sentiment": sent,
                        },
                    )
                except requests.RequestException as exc:
                    st.error(f"Could not reach API: {exc}")
                    r = None
                if r is not None:
                    if r.status_code != 200:
                        st.error(f"API error {r.status_code}: {r.text}")
                    else:
                        rec_data = r.json()
                        rows: List[Dict[str, Any]] = rec_data.get("recommendations", [])
                        st.dataframe(rows, use_container_width=True)
                        st.info(rec_data.get("disclaimer") or DISCLAIMER_FALLBACK)

        with col_b:
            if st.button("Fetch trends"):
                try:
                    t = _get(f"/api/trends/{cid.strip()}")
                except requests.RequestException as exc:
                    st.error(f"Could not reach API: {exc}")
                    t = None
                if t is not None:
                    if t.status_code != 200:
                        st.error(f"API error {t.status_code}: {t.text}")
                    else:
                        trend_data = t.json()
                        series: List[Dict[str, Any]] = trend_data.get("trends", [])
                        st.info(trend_data.get("disclaimer") or DISCLAIMER_FALLBACK)
                        if not series:
                            st.write("No prediction history for this patient.")
                        else:
                            frame = pd.DataFrame(
                                [
                                    {
                                        "entry": i,
                                        "confidence": row["confidence"],
                                        "risk_level": row["risk_level"],
                                    }
                                    for i, row in enumerate(series)
                                ]
                            )
                            chart = (
                                alt.Chart(frame)
                                .mark_line(point=True)
                                .encode(
                                    x=alt.X("entry:Q", title="Entry order"),
                                    y=alt.Y("confidence:Q", title="Confidence"),
                                    tooltip=["risk_level:N", "confidence:Q"],
                                )
                            )
                            st.altair_chart(chart, use_container_width=True)


if __name__ == "__main__":
    main()
