"""
Central configuration for the SE-CDSS backend modules.
This file keeps paths, thresholds, weights, and constants in one place.
"""

import os
from typing import Dict, List

from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT: str = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC_DIR: str = os.path.join(PROJECT_ROOT, "src")
DATA_DIR: str = os.path.join(PROJECT_ROOT, "data")
RAW_DATA_DIR: str = os.path.join(DATA_DIR, "raw")
PROCESSED_DATA_DIR: str = os.path.join(DATA_DIR, "processed")
MODEL_DIR: str = os.path.join(PROJECT_ROOT, "models", "baseline")

TRAIN_RAW_PATH: str = os.path.join(RAW_DATA_DIR, "drugsComTrain_raw.csv")
TEST_RAW_PATH: str = os.path.join(RAW_DATA_DIR, "drugsComTest_raw.csv")
TRAIN_PROCESSED_PATH: str = os.path.join(PROCESSED_DATA_DIR, "train_processed.csv")
TEST_PROCESSED_PATH: str = os.path.join(PROCESSED_DATA_DIR, "test_processed.csv")

MODEL_PATH: str = os.path.join(MODEL_DIR, "model.pkl")
VECTORIZER_PATH: str = os.path.join(MODEL_DIR, "vectorizer.pkl")
CONFUSION_MATRIX_PATH: str = os.path.join(MODEL_DIR, "confusion_matrix.png")

DATABASE_URL: str = os.getenv("DATABASE_URL", "sqlite:///./se_cdss.db")

NEUTRAL_CONFIDENCE_THRESHOLD: float = 0.6
NEGATIVE_SEVERE_THRESHOLD: float = 0.75

DEFAULT_RECOMMENDATION_WEIGHTS: Dict[str, float] = {
    "w1_guideline": 0.33,
    "w2_ehr": 0.33,
    "w3_sentiment": 0.33,
}

ADVERSE_EVENT_KEYWORDS: List[str] = [
    "rash",
    "chest pain",
    "difficulty breathing",
    "swelling",
    "stopped taking",
    "severe",
    "emergency",
    "hospital",
    "reaction",
    "allergic",
]

DISCLAIMER_TEXT: str = (
    "This output is generated by an AI-assisted decision support system. "
    "It is advisory only. The final clinical decision must always be made by "
    "a qualified healthcare professional."
)
