"""
Central configuration for the SE-CDSS backend modules.
This file keeps paths, thresholds, weights, and constants in one place.
"""

import os
from typing import Dict, List

from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT: str = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC_DIR: str = os.path.join(PROJECT_ROOT, "src")
DATA_DIR: str = os.path.join(PROJECT_ROOT, "data")
RAW_DATA_DIR: str = os.path.join(DATA_DIR, "raw")
PROCESSED_DATA_DIR: str = os.path.join(DATA_DIR, "processed")
SIMULATED_EHR_DIR: str = os.path.join(DATA_DIR, "simulated_ehr")
SIMULATED_EHR_PATH: str = os.path.join(SIMULATED_EHR_DIR, "patients.json")
MODEL_DIR: str = os.path.join(PROJECT_ROOT, "models", "baseline")

TRAIN_RAW_PATH: str = os.path.join(RAW_DATA_DIR, "drugsComTrain_raw.csv")
TEST_RAW_PATH: str = os.path.join(RAW_DATA_DIR, "drugsComTest_raw.csv")
TRAIN_PROCESSED_PATH: str = os.path.join(PROCESSED_DATA_DIR, "train_processed.csv")
TEST_PROCESSED_PATH: str = os.path.join(PROCESSED_DATA_DIR, "test_processed.csv")

MODEL_PATH: str = os.path.join(MODEL_DIR, "model.pkl")
VECTORIZER_PATH: str = os.path.join(MODEL_DIR, "vectorizer.pkl")
CONFUSION_MATRIX_PATH: str = os.path.join(MODEL_DIR, "confusion_matrix.png")

DATABASE_URL: str = os.getenv("DATABASE_URL", "sqlite:///./se_cdss.db")

JWT_SECRET: str = os.getenv("JWT_SECRET", "se-cdss-dev-secret-change-in-production")
JWT_ALGORITHM: str = "HS256"
JWT_EXPIRE_HOURS: int = 24

CONFIDENCE_THRESHOLD_MED: float = 0.60
CONFIDENCE_THRESHOLD_HIGH: float = 0.75

NEUTRAL_CONFIDENCE_THRESHOLD: float = CONFIDENCE_THRESHOLD_MED
NEGATIVE_SEVERE_THRESHOLD: float = CONFIDENCE_THRESHOLD_HIGH

RECOMMENDATION_WEIGHTS: Dict[str, float] = {"w1": 0.33, "w2": 0.33, "w3": 0.33}

DEFAULT_RECOMMENDATION_WEIGHTS: Dict[str, float] = {
    "w1_guideline": RECOMMENDATION_WEIGHTS["w1"],
    "w2_ehr": RECOMMENDATION_WEIGHTS["w2"],
    "w3_sentiment": RECOMMENDATION_WEIGHTS["w3"],
}

SENTIMENT_SCORE_MAP: Dict[str, float] = {
    "positive": 1.0,
    "neutral": 0.5,
    "negative": 0.0,
}

ADVERSE_KEYWORDS: List[str] = [
    "rash",
    "chest pain",
    "difficulty breathing",
    "swelling",
    "stopped taking",
    "severe",
    "emergency",
    "hospital",
    "reaction",
    "allergic",
]

ADVERSE_EVENT_KEYWORDS: List[str] = ADVERSE_KEYWORDS

DISCLAIMER_TEXT: str = (
    "This output is generated by an AI-assisted decision support system. "
    "It is advisory only. The final clinical decision must always be made by "
    "a qualified healthcare professional."
)

DRUG_MAP: Dict[str, List[str]] = {
    "hypertension": [
        "Amlodipine",
        "Lisinopril",
        "Losartan",
        "Hydrochlorothiazide",
        "Atenolol",
    ],
    "diabetes": [
        "Metformin",
        "Glipizide",
        "Sitagliptin",
        "Insulin Glargine",
        "Empagliflozin",
    ],
    "depression": [
        "Sertraline",
        "Fluoxetine",
        "Escitalopram",
        "Amitriptyline",
        "Venlafaxine",
    ],
    "malaria": [
        "Artemether-Lumefantrine",
        "Quinine",
        "Chloroquine",
        "Doxycycline",
        "Atovaquone",
    ],
    "respiratory": [
        "Amoxicillin",
        "Azithromycin",
        "Salbutamol",
        "Prednisolone",
        "Doxycycline",
    ],
}

TARGET_CONDITIONS: List[str] = list(DRUG_MAP.keys())

# Clinical guideline fit scores (0.0–1.0) per condition and drug; static lookup for dissertation baseline.
GUIDELINE_SCORES: Dict[str, Dict[str, float]] = {
    "hypertension": {
        "Amlodipine": 0.92,
        "Lisinopril": 0.88,
        "Losartan": 0.85,
        "Hydrochlorothiazide": 0.80,
        "Atenolol": 0.72,
    },
    "diabetes": {
        "Metformin": 0.95,
        "Glipizide": 0.78,
        "Sitagliptin": 0.82,
        "Insulin Glargine": 0.90,
        "Empagliflozin": 0.86,
    },
    "depression": {
        "Sertraline": 0.88,
        "Fluoxetine": 0.87,
        "Escitalopram": 0.89,
        "Amitriptyline": 0.70,
        "Venlafaxine": 0.84,
    },
    "malaria": {
        "Artemether-Lumefantrine": 0.94,
        "Quinine": 0.78,
        "Chloroquine": 0.65,
        "Doxycycline": 0.80,
        "Atovaquone": 0.76,
    },
    "respiratory": {
        "Amoxicillin": 0.88,
        "Azithromycin": 0.85,
        "Salbutamol": 0.90,
        "Prednisolone": 0.75,
        "Doxycycline": 0.82,
    },
}
